name: fyp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gymnasium
  - stable-baselines3
  - tensorboard
  - pyyaml
  - pip
  - pip:
    - minigrid
  - requests
  - python-dotenv
  - tenacity